name: "Build"

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Set up cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build binary (x86_64-apple-darwin)
        run: |
          rustup target add x86_64-apple-darwin
          cargo build --release --target x86_64-apple-darwin

      - name: Archive created binary
        uses: actions/upload-artifact@v4
        with:
          name: tmoverlook_x86_64-apple-darwin
          path: ./target/x86_64-apple-darwin/release/tmoverlook

      - name: Build binary (aarch64-apple-darwin)
        run: |
          rustup target add aarch64-apple-darwin
          cargo build --release --target aarch64-apple-darwin

      - name: Archive created binary
        uses: actions/upload-artifact@v4
        with:
          name: tmoverlook_aarch64-apple-darwin
          path: ./target/aarch64-apple-darwin/release/tmoverlook
