name: "Check"

on:
  workflow_dispatch:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: "true"

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Set up cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Check formatting
        run: cargo fmt --check

      - name: Check clippy
        run: |
          cargo clippy -- \
          -D clippy::all \
          -D clippy::pedantic \
          -A clippy::redundant_closure \
          -A clippy::redundant_closure_for_method_calls \
          -A clippy::too-many-lines

      - name: Execute tests
        run: cargo test
