name: "Release"

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
        # Push events to any matching semantic version tag.
        # For example, 1.10.1 or 2.0.0 or 3.0.0-alpha.

jobs:
  release:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Set up cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build binary (x86_64-apple-darwin)
        run: |
          rustup target add x86_64-apple-darwin
          cargo build --release --target x86_64-apple-darwin

      - name: Archive created binary
        uses: actions/upload-artifact@v4
        with:
          name: tmoverlook_x86_64-apple-darwin
          path: ./target/x86_64-apple-darwin/release/tmoverlook

      - name: Build binary (aarch64-apple-darwin)
        run: |
          rustup target add aarch64-apple-darwin
          cargo build --release --target aarch64-apple-darwin

      - name: Archive created binary
        uses: actions/upload-artifact@v4
        with:
          name: tmoverlook_aarch64-apple-darwin
          path: ./target/aarch64-apple-darwin/release/tmoverlook

      - name: Move binary to release directory
        run: |
          mkdir -p release
          mv ./target/x86_64-apple-darwin/release/tmoverlook ./release/tmoverlook_x86_64-apple-darwin
          mv ./target/aarch64-apple-darwin/release/tmoverlook ./release/tmoverlook_aarch64-apple-darwin

      - name: Build changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: "release-changelog-builder-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: ${{steps.changelog.outputs.changelog}}
          draft: false
          prerelease: false
          files: |
            ./release/tmoverlook_x86_64-apple-darwin
            ./release/tmoverlook_aarch64-apple-darwin
